language: node_js
node_js:
- '4'
env:
  global:
    secure: ajxHlKd3XEECvyj3mY/4ff2T8qUFYYnmqgEWHiC5rj23dyw+JpHQnIyYKODhhOZdTpkDuMHgirnKmM2/0vBHTir0u8D74y70cyb6y/b34XbDTxRA+2B9imNKdEuE0iM8ULA77AsH/VEhorzmq2oUv4Pum/7714yfJyjRLw2j3rKJxa50xZ2pV/x8WIves21MZ0UgWQADtZCGvMZa0MwWc+fO2dWxnDWQt1Oe6505qzKFa3dcvI/YeVoaNO1fFfoK/1HeSh1rRFtr+xU9DU3ZzeSLZPIDrQYJoxkZ3nD1PNKGLnquokqpo6jRyMpLcNLuF6hJS+TJ7KFWQVfvdgiavblQ9Sbz+2nZGYbc+j5ULdZVwX8KxLZUSe+UyqN/+6+yOLYjOpflXPeDl1PTDNurGfgba7o0uUwDIzKe4AG9FPrqDRf3lBxGMx9wm/0IsibWTgmDp/uv76j/4oD31w3jN8D0Hwj/UEwy3m1mPAoEdvjoAwohhebTsdMAzVOFi6ofDjIwiKUvFQ8RDeqKs0GyY2Auwr6sxX2cbjG1BwgW+8me1R2HLDTsjpDy8CfSaQaEUtX6AFwjqWEL5i3U25p82s4xwxiHr4Rxz1lUT8C9ua3QFH6x7kdQSbEXV98sGok0djeQ3UkHdvDsKjM/3rf0cogwfKFRIRbkpAUpf2g3XzE=
before_install: 
before_script:
- npm test
script: 
deploy:
  provider: heroku
  api_key:
    secure: UUSSUjrmlhBT95ysmSktPUh78TvcMvulBSzQ39l0goWP1qfb57qSNQzlHYfIO3HPAhAs25AJJt5KXps9/coCoW9Fvjs+G+W0d5zDDoBtsuXyHbBusBdvsjzAY2h9fdNq2+DNgu2HTUpTtrA1wDooGChremRuH6arrhBf6vxSwIIDhXvB5VqCJjBnEFiQ1SJRxoMGMNI8pYK58kuCRh1uTJJQXPf/IHpBQPEheR38R9RI91aWai8pGHI89frckmr/sU5OjigqgXbhsfT98R2SwyuRC7vH/DHWLhRbneYdDNL/7imkM5gRpkl1CFwuc2e3rAWGbMZbZKeyxExjsJj58CfPa5icpKDJ113SB50eigb6KSR3Gq7WtT0AWBmOHcMOQ6RIU5/+mpaIHhWJknfa5fzPOX1eFONYgBc0vFVrrBjYPt24TdbTTxQIlokLgpGpW7KWahOF0HJ/VwuqwKOt1vVV/RF951Ome4BYw1apE7p0JUGXIXqD+ArYnazddGVpl2Eis8xdk4QghpqOSpod6j+Xdvf8yJatI5i8pasTX2mBlkvxB8hDVFRLm4Hqt/sOvc1Z7vNe2qf0khdJCXFNkUotHFshebzcO9sPeLv4eDL5lr9CFcgameClTwAnlR4QyYXvztKkj2f0VEyATP7Xb8k2S9jfYmr1uTXM1yp3jFc=
  app: ocp-server
  on:
    repo: open-contracting-partnership/ocp-form-server
    branch: master
